# Generated by Django 3.1.3 on 2020-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('LabelId', models.AutoField(primary_key=True, serialize=False)),
                ('LabelName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=50)),
            ],
        ),
    ]
